# Generated by Django 5.0.4 on 2024-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=20)),
                ('monthly_count_blob', models.JSONField()),
            ],
            options={
                'unique_together': {('city', 'state')},
            },
        ),
    ]
