# Generated by Django 5.0.4 on 2024-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcon',
            name='monthly_median_sales_price_blob',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
