# Generated by Django 5.0.4 on 2024-04-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildtrack', '0003_regcon_monthly_mean_sales_price_persqft_blob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regcon',
            old_name='monthly_count_blob',
            new_name='monthly_sales_count_blob',
        ),
    ]
