# Generated by Django 5.0.4 on 2024-04-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildtrack', '0004_rename_monthly_count_blob_regcon_monthly_sales_count_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regcon',
            name='monthly_mean_sales_price_blob',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='regcon',
            name='monthly_median_sales_price_blob',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='regcon',
            name='monthly_median_sales_price_persqft_blob',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='regcon',
            name='monthly_sales_count_blob',
            field=models.JSONField(null=True),
        ),
    ]
